# Generated by Django 4.2.7 on 2023-12-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
