# Generated by Django 4.2.7 on 2023-12-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0004_news_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='no',
        ),
    ]
