steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'secrets'
      - 'versions'
      - 'add'
      - 'env-knowze'
      - --data-file='.env'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'secrets'
      - 'versions'
      - 'add'
      - 'firabase-credential'
      - --data-file='utils/cred.json'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sonic-anagram-397306/knowze_web_monolith', 'deployment']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sonic-anagram-397306/knowze_web_monolith']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'knowze_web_prod', '--image', 'gcr.io/sonic-anagram-397306/knowze_web_monolith', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

images:
  - 'gcr.io/sonic-anagram-397306/knowze_web_monolith:v1'
