steps:

- name : 'gcr.io/cloud-builders/docker'
  args : ['build', '-t', 'gcr.io/sonic-anagram-397306/knowze_web', '.']

- name : 'gcr.io/cloud-builders/docker'
  args : ['push', 'gcr.io/sonic-anagram-397306/knowze_web']

- name : 'gcr.io/cloud-builders/gcloud'
  args : ['run', 'deploy', 'knowze_web', '--image', 'gcr.io/sonic-anagram-397306/knowze_web', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

images : 
  - 'gcr.io/sonic-anagram-397306/knowze_web'