FROM python:3.11.4-bullseye

LABEL path="cc-team"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . /app

WORKDIR /app

RUN python3 -m pip install --upgrade pip

RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "-c", "deployment/gunicorn_config.py", "django_app.wsgi:application", "--preload"], 