# Generated by Django 4.2.7 on 2023-11-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_content_text_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='theme_activity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='type_activity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtitle',
            name='shortdesc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
