# Generated by Django 4.2.7 on 2023-11-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
