# Generated by Django 4.2.7 on 2023-11-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
